SOURCE_IO := idm_cmd_common.c idm_nvme_io.c idm_nvme_utils.c async_nvme.c
SOURCE_API := $(SOURCE_IO) idm_nvme_api.c

idm_nvme_api : $(SOURCE_API)
	echo Compile $@
	gcc $(SOURCE_API) -o $@ -pthread

idm_nvme_io : $(SOURCE_IO)
	echo Compile $@
	gcc $(SOURCE_IO) -o $@

idm_nvme_io_admin : idm_nvme_io_admin.c
	echo Compile $@
	gcc idm_nvme_io_admin.c -o $@

